### ISSUE TITLE
marimo.pyの出力フォーマット変更

### ISSUE THREAD

**Issue by quojama** [quojama/takohachi#11]
marimotime.py `!!mt`
の出力フォーマットを変更したく作成当初色々試してみたがわからずそのまま放置していました。初歩中の初歩だとおもいますが...

```
marimo time = 07/12 22:10
(In Japan = 07/13 11:10)
```
の時間フォーマットについて、不要な頭の0を取りたいです。この場合だと
```
marimo time = 7/12 22:10
(In Japan = 7/13 11:10)
```
としたい。月、日、時、分すべて。

16行目のここだと思うんだけど...
`await ctx.send(f"marimo time = {now.strftime('**%m/%d %H:%M**')}\n(In Japan = {JST.strftime('%m/%d %H:%M')})")`

give me your help :)

**Comment by johnmanjiro13** [comment]
こんにちは。strftimeを使うとどうしても0埋めしてしまい、文字列を処理する必要がでてきます。
下記のようにformatでやってしまうのはどうでしょう？

```python
await ctx.send(f"marimo time = {'**{d.month}/{d.day} {d.hour}:{d.minute:}**'.format(d=now)}\n(In Japan = {'{d.month}/{d.day} {d.hour}:{d.minute:02}'.format(d=JST)})")
```

**Comment by quojama** [comment]
こんにちわ！見つけていただきありがとうございます。初中の初の初学者で大変ありがたいです。
やはりstrftimeは0をつけてしまうんですね...。なんとなくそんな気がしていました。
解決案もありがとうございます！早速後ほどためしてみます。学ばせていただきます！
