### ISSUE TITLE
save_image.pyのembedを豪華にいい感じに

### ISSUE THREAD

**Issue by quojama** [quojama/takohachi#15]
近々やってPRしまっせ  
ᕦ(+_+;)ᕤ =333

**Comment by quojama** [comment]
@zztkm embedブランチでsave_image.pyの更新をpushしてみたがどうだろう？

**Comment by zztkm** [comment]
@quojama いい感じだと思います。
段取りあってます。

仮に本番PR前に誰かに進捗を見てもらいたい場合はDraft PRというやり方もあるので参考までに
https://qiita.com/tatane616/items/13da1b6797a7b871ad58

**Comment by quojama** [comment]
@zztkm ありがとう。理解できましたよ。

53,67行目
```python
# 本当はこのthumbnailは毎回その該当の画像になるようにしたい...               embed.set_thumbnail(url="https://cdn.discordapp.com/attachments/814524400832741437/861511918219821056/image0.jpg")```

これ調べたり考えたりしたけどわからんかった（泣）attachmentのURLさえ取得できればいいと思うんだけどなー

**Comment by zztkm** [comment]
@quojama 

以下が参考になりそうです。

https://discordpy.readthedocs.io/en/latest/api.html?highlight=fetch_message#discord.Attachment.url

例:
(テストしてないですがこれでいけませんかね？)
```python
embed.set_thumbnail(url=attachment.url)
```
